[tool.poetry]
name = "Shakespeare"
version = "0.1"
description = "poetry test project"
authors = ["warder <eng@warder.io>"]

[tool.poetry.dependencies]
python="^3.8"
requests="2.19"


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"